#!/usr/bin/env python3
"""Generate Go, PHP, and Python packages from canonical YAML taxonomy files."""

import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_DIR = ROOT / "schema"
GEN_GO = ROOT / "generated" / "go" / "taxonomy"
GEN_PHP = ROOT / "generated" / "php" / "src"
GEN_PY = ROOT / "generated" / "python" / "indigenous_taxonomy"

HEADER_GO = "// Code generated by scripts/generate.py. DO NOT EDIT.\n"
HEADER_PHP = "<?php\n\n// Code generated by scripts/generate.py. DO NOT EDIT.\n\ndeclare(strict_types=1);\n\nnamespace IndigenousTaxonomy;\n"
HEADER_PY = '"""Code generated by scripts/generate.py. DO NOT EDIT."""\n'


def load_yaml(name: str) -> dict:
    with open(SCHEMA_DIR / f"{name}.yaml") as f:
        return yaml.safe_load(f)


def schema_hash() -> str:
    h = hashlib.sha256()
    for name in sorted(SCHEMA_DIR.glob("*.yaml")):
        h.update(name.read_bytes())
    return h.hexdigest()[:16]


def to_pascal(slug: str) -> str:
    return "".join(word.capitalize() for word in re.split(r"[-:]", slug))


def to_upper_snake(slug: str) -> str:
    return re.sub(r"[-:]", "_", slug).upper()


def to_go_const(slug: str) -> str:
    return "Category" + to_pascal(slug)


# --- Go generation ---


def gen_go_categories(cats: list[dict]) -> str:
    lines = [HEADER_GO, "package taxonomy\n", "type Category string\n", "const ("]
    for c in cats:
        lines.append(f'\t{to_go_const(c["slug"])} Category = "{c["slug"]}"')
    lines.append(")\n")
    lines.append("var AllCategories = []Category{")
    lines.append("\t" + ", ".join(to_go_const(c["slug"]) for c in cats) + ",")
    lines.append("}\n")
    lines.append("func IsValidCategory(s string) bool {")
    lines.append("\tfor _, c := range AllCategories {")
    lines.append('\t\tif string(c) == s { return true }')
    lines.append("\t}")
    lines.append("\treturn false")
    lines.append("}\n")
    lines.append("func RoutableCategories() []Category {")
    lines.append("\treturn []Category{")
    for c in cats:
        if c.get("nc_routing"):
            lines.append(f"\t\t{to_go_const(c['slug'])},")
    lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def flatten_regions(regions: list[dict], out: list[dict] | None = None) -> list[dict]:
    if out is None:
        out = []
    for r in regions:
        out.append({"slug": r["slug"], "name": r["name"]})
        if "children" in r:
            flatten_regions(r["children"], out)
    return out


def build_parent_map(regions: list[dict]) -> dict[str, str]:
    """Walk the children: tree and return a flat dict mapping each child slug to its direct parent slug.

    Top-level entries (e.g. 'canada') do NOT appear as keys so that ParentRegion
    returns (false, "") for them.  Output is sorted for deterministic code emission.
    """
    result: dict[str, str] = {}

    def _walk(nodes: list[dict], parent_slug: str | None) -> None:
        for node in nodes:
            slug = node["slug"]
            if parent_slug is not None:
                result[slug] = parent_slug
            if "children" in node:
                _walk(node["children"], slug)

    _walk(regions, None)
    return dict(sorted(result.items()))


def gen_go_regions(regions: list[dict]) -> str:
    flat = flatten_regions(regions)
    parent_map = build_parent_map(regions)
    lines = [HEADER_GO, "package taxonomy\n", "type Region string\n", "const ("]
    for r in flat:
        lines.append(f'\tRegion{to_pascal(r["slug"])} Region = "{r["slug"]}"')
    lines.append(")\n")
    lines.append("var AllRegions = []Region{")
    lines.append("\t" + ", ".join(f'Region{to_pascal(r["slug"])}' for r in flat) + ",")
    lines.append("}\n")
    lines.append("func IsValidRegion(s string) bool {")
    lines.append("\tfor _, r := range AllRegions {")
    lines.append('\t\tif string(r) == s { return true }')
    lines.append("\t}")
    lines.append("\treturn false")
    lines.append("}\n")
    lines.append("var regionParents = map[Region]Region{")
    for child, parent in parent_map.items():
        lines.append(f'\tRegion{to_pascal(child)}: Region{to_pascal(parent)},')
    lines.append("}\n")
    lines.append("// ParentRegion returns the direct parent of child in the region hierarchy.")
    lines.append("// Top-level regions (e.g. RegionCanada) return (\"\", false).")
    lines.append("func ParentRegion(child Region) (Region, bool) {")
    lines.append("\tp, ok := regionParents[child]")
    lines.append("\treturn p, ok")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_go_treaties(treaties: list[dict]) -> str:
    # Sort by slug for deterministic output (treaty:1, treaty:10, treaty:11, treaty:2 … is lex order,
    # so sort numerically by the integer suffix instead).
    sorted_treaties = sorted(treaties, key=lambda t: int(t["slug"].split(":")[1]))
    lines = [HEADER_GO, "package taxonomy\n", "type Treaty string\n", "const ("]
    for t in sorted_treaties:
        num = t["slug"].split(":")[1]
        lines.append(f'\tTreatyArea{num} Treaty = "{t["slug"]}"')
    lines.append(")\n")
    lines.append("var AllTreaties = []Treaty{")
    lines.append("\t" + ", ".join(f'TreatyArea{t["slug"].split(":")[1]}' for t in sorted_treaties) + ",")
    lines.append("}\n")
    lines.append("func IsValidTreaty(s string) bool {")
    lines.append("\tvalidTreaties := map[Treaty]struct{}{}")
    lines.append("\tfor _, t := range AllTreaties {")
    lines.append("\t\tvalidTreaties[t] = struct{}{}")
    lines.append("\t}")
    lines.append("\t_, ok := validTreaties[Treaty(s)]")
    lines.append("\treturn ok")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_go_dialects(families: list[dict]) -> str:
    lines = [HEADER_GO, "package taxonomy\n"]
    lines.append("type DialectCode struct {")
    lines.append("\tCode       string")
    lines.append("\tName       string")
    lines.append("\tDisplayName string")
    lines.append("\tISO639_3   string")
    lines.append("\tFamily     string")
    lines.append("\tRegions    []Region")
    lines.append("}\n")
    lines.append("var AllDialects = []DialectCode{")
    for fam in families:
        for d in fam["dialects"]:
            regions = ", ".join(f'"{r}"' for r in d["regions"])
            lines.append(f'\t{{Code: "{d["code"]}", Name: "{d["name"]}", DisplayName: "{d["display_name"]}", ISO639_3: "{d["iso_639_3"]}", Family: "{fam["slug"]}", Regions: []Region{{{regions}}}}},')
    lines.append("}\n")
    lines.append("func DialectByCode(code string) (DialectCode, bool) {")
    lines.append("\tfor _, d := range AllDialects {")
    lines.append('\t\tif d.Code == code { return d, true }')
    lines.append("\t}")
    lines.append("\treturn DialectCode{}, false")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_go_version(version: str, sha: str) -> str:
    lines = [HEADER_GO, "package taxonomy\n"]
    lines.append(f'const TaxonomyVersion = "{version}"')
    lines.append(f'const SchemaHash = "{sha}"')
    return "\n".join(lines) + "\n"


# --- PHP generation ---


def gen_php_categories(cats: list[dict]) -> str:
    lines = [HEADER_PHP, "enum Category: string\n{"]
    for c in cats:
        lines.append(f"    case {to_pascal(c['slug'])} = '{c['slug']}';")
    lines.append("")
    lines.append("    /** @return list<self> */")
    lines.append("    public static function routable(): array")
    lines.append("    {")
    lines.append("        return [")
    for c in cats:
        if c.get("nc_routing"):
            lines.append(f"            self::{to_pascal(c['slug'])},")
    lines.append("        ];")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_php_regions(regions: list[dict]) -> str:
    flat = flatten_regions(regions)
    lines = [HEADER_PHP, "enum Region: string\n{"]
    for r in flat:
        lines.append(f"    case {to_pascal(r['slug'])} = '{r['slug']}';")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_php_dialects(families: list[dict]) -> str:
    lines = [HEADER_PHP]
    lines.append("final class DialectCode\n{")
    lines.append("    /** @param list<string> $regions */")
    lines.append("    public function __construct(")
    lines.append("        public readonly string $code,")
    lines.append("        public readonly string $name,")
    lines.append("        public readonly string $displayName,")
    lines.append("        public readonly string $iso6393,")
    lines.append("        public readonly string $family,")
    lines.append("        public readonly array $regions,")
    lines.append("    ) {}")
    lines.append("")
    lines.append("    /** @return list<self> */")
    lines.append("    public static function all(): array")
    lines.append("    {")
    lines.append("        return [")
    for fam in families:
        for d in fam["dialects"]:
            regions = ", ".join(f"'{r}'" for r in d["regions"])
            lines.append(f"            new self('{d['code']}', '{d['name']}', '{d['display_name']}', '{d['iso_639_3']}', '{fam['slug']}', [{regions}]),")
    lines.append("        ];")
    lines.append("    }")
    lines.append("")
    lines.append("    public static function byCode(string $code): ?self")
    lines.append("    {")
    lines.append("        foreach (self::all() as $d) {")
    lines.append("            if ($d->code === $code) { return $d; }")
    lines.append("        }")
    lines.append("        return null;")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_php_version(version: str, sha: str) -> str:
    lines = [HEADER_PHP, "final class TaxonomyVersion\n{"]
    lines.append(f"    public const VERSION = '{version}';")
    lines.append(f"    public const SCHEMA_HASH = '{sha}';")
    lines.append("}")
    return "\n".join(lines) + "\n"


# --- Python generation ---


def gen_py_categories(cats: list[dict]) -> str:
    lines = [HEADER_PY, "from enum import Enum\n\n"]
    lines.append("class Category(str, Enum):")
    for c in cats:
        lines.append(f'    {to_upper_snake(c["slug"])} = "{c["slug"]}"')
    lines.append("")
    lines.append("    @classmethod")
    lines.append("    def routable(cls) -> list['Category']:")
    lines.append("        return [")
    for c in cats:
        if c.get("nc_routing"):
            lines.append(f"            cls.{to_upper_snake(c['slug'])},")
    lines.append("        ]")
    return "\n".join(lines) + "\n"


def gen_py_regions(regions: list[dict]) -> str:
    flat = flatten_regions(regions)
    lines = [HEADER_PY, "from enum import Enum\n\n"]
    lines.append("class Region(str, Enum):")
    for r in flat:
        lines.append(f'    {to_upper_snake(r["slug"])} = "{r["slug"]}"')
    return "\n".join(lines) + "\n"


def gen_py_dialects(families: list[dict]) -> str:
    lines = [HEADER_PY, "from dataclasses import dataclass, field\n\n"]
    lines.append("@dataclass(frozen=True)")
    lines.append("class DialectCode:")
    lines.append("    code: str")
    lines.append("    name: str")
    lines.append("    display_name: str")
    lines.append("    iso_639_3: str")
    lines.append("    family: str")
    lines.append("    regions: list[str] = field(default_factory=list)")
    lines.append("")
    lines.append("")
    lines.append("ALL_DIALECTS: list[DialectCode] = [")
    for fam in families:
        for d in fam["dialects"]:
            regions = ", ".join(f'"{r}"' for r in d["regions"])
            lines.append(f'    DialectCode("{d["code"]}", "{d["name"]}", "{d["display_name"]}", "{d["iso_639_3"]}", "{fam["slug"]}", [{regions}]),')
    lines.append("]\n")
    lines.append("")
    lines.append("def dialect_by_code(code: str) -> DialectCode | None:")
    lines.append("    return next((d for d in ALL_DIALECTS if d.code == code), None)")
    return "\n".join(lines) + "\n"


def gen_py_version(version: str, sha: str) -> str:
    lines = [HEADER_PY]
    lines.append(f'TAXONOMY_VERSION = "{version}"')
    lines.append(f'SCHEMA_HASH = "{sha}"')
    return "\n".join(lines) + "\n"


def gen_py_init() -> str:
    return '"""Indigenous Taxonomy — generated from canonical YAML schemas."""\n\nfrom .version import TAXONOMY_VERSION, SCHEMA_HASH\nfrom .categories import Category\nfrom .regions import Region\nfrom .dialects import DialectCode, ALL_DIALECTS, dialect_by_code\n\n__all__ = [\n    "TAXONOMY_VERSION",\n    "SCHEMA_HASH",\n    "Category",\n    "Region",\n    "DialectCode",\n    "ALL_DIALECTS",\n    "dialect_by_code",\n]\n'


# --- Main ---


def main() -> None:
    cats_data = load_yaml("categories")
    regions_data = load_yaml("regions")
    dialects_data = load_yaml("dialect-codes")
    treaties_data = load_yaml("treaties")

    sha = schema_hash()
    version = cats_data.get("version", 1)
    version_str = f"{version}.0.0"

    # Go
    GEN_GO.mkdir(parents=True, exist_ok=True)
    (GEN_GO / "categories.go").write_text(gen_go_categories(cats_data["categories"]))
    (GEN_GO / "regions.go").write_text(gen_go_regions(regions_data["regions"]))
    (GEN_GO / "dialects.go").write_text(gen_go_dialects(dialects_data["language_families"]))
    (GEN_GO / "treaties.go").write_text(gen_go_treaties(treaties_data["treaties"]))
    (GEN_GO / "version.go").write_text(gen_go_version(version_str, sha))

    # PHP
    GEN_PHP.mkdir(parents=True, exist_ok=True)
    (GEN_PHP / "Category.php").write_text(gen_php_categories(cats_data["categories"]))
    (GEN_PHP / "Region.php").write_text(gen_php_regions(regions_data["regions"]))
    (GEN_PHP / "DialectCode.php").write_text(gen_php_dialects(dialects_data["language_families"]))
    (GEN_PHP / "TaxonomyVersion.php").write_text(gen_php_version(version_str, sha))

    # Python
    GEN_PY.mkdir(parents=True, exist_ok=True)
    (GEN_PY / "__init__.py").write_text(gen_py_init())
    (GEN_PY / "categories.py").write_text(gen_py_categories(cats_data["categories"]))
    (GEN_PY / "regions.py").write_text(gen_py_regions(regions_data["regions"]))
    (GEN_PY / "dialects.py").write_text(gen_py_dialects(dialects_data["language_families"]))
    (GEN_PY / "version.py").write_text(gen_py_version(version_str, sha))

    print(f"Generated taxonomy v{version_str} (hash: {sha})")
    print(f"  Go:     {GEN_GO}")
    print(f"  PHP:    {GEN_PHP}")
    print(f"  Python: {GEN_PY}")


if __name__ == "__main__":
    main()
